/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.internal.swig;

public class RcClient {
  public static int createEngineBuilder(RcimEngineBuilderParam param, long[] OUTPUT) {
    return RcClientJNI.createEngineBuilder(RcimEngineBuilderParam.getCPtr(param), param, OUTPUT);
  }

  public static int engineBuilderBuild(long builderPtr, long[] OUTPUT) {
    return RcClientJNI.engineBuilderBuild(builderPtr, OUTPUT);
  }

  public static long newSdkVersionArray(int size) {
    return RcClientJNI.newSdkVersionArray(size);
  }

  public static void insertSdkVersionArray(long ptr, long[] ptrArr, int size) {
    RcClientJNI.insertSdkVersionArray(ptr, ptrArr, size);
  }

  public static void freeSdkVersionArray(long ptr) {
    RcClientJNI.freeSdkVersionArray(ptr);
  }

  public static int engineBuilderSetStorePath(long builderPtr, String storePath) {
    return RcClientJNI.engineBuilderSetStorePath(builderPtr, storePath);
  }

  public static int engineBuilderSetAreaCode(long builderPtr, int areaCode) {
    return RcClientJNI.engineBuilderSetAreaCode(builderPtr, areaCode);
  }

  public static int engineBuilderSetNaviServer(long builderPtr, RcimStringVector naviVec) {
    return RcClientJNI.engineBuilderSetNaviServer(builderPtr, RcimStringVector.getCPtr(naviVec), naviVec);
  }

  public static int engineBuilderSetStatisticServer(long builderPtr, String StatisticServer) {
    return RcClientJNI.engineBuilderSetStatisticServer(builderPtr, StatisticServer);
  }

  public static int engineBuilderSetCloudType(long builderPtr, int cloudType) {
    return RcClientJNI.engineBuilderSetCloudType(builderPtr, cloudType);
  }

  public static int engineBuilderSetDbEncrypted(long builderPtr, boolean encrypted) {
    return RcClientJNI.engineBuilderSetDbEncrypted(builderPtr, encrypted);
  }

  public static int engineBuilderSetEnableGroupCall(long builderPtr, boolean enable) {
    return RcClientJNI.engineBuilderSetEnableGroupCall(builderPtr, enable);
  }

  public static int engineBuilderSetEnableReconnectKick(long builderPtr, boolean enable) {
    return RcClientJNI.engineBuilderSetEnableReconnectKick(builderPtr, enable);
  }

  public static int engineBuilderSetFilePath(long builderPtr, String filePath) {
    return RcClientJNI.engineBuilderSetFilePath(builderPtr, filePath);
  }

  public static int engineBuilderSetNetworkEnv(long builderPtr, String networkEnv) {
    return RcClientJNI.engineBuilderSetNetworkEnv(builderPtr, networkEnv);
  }

  public static void engineConnect(long enginePtr, String token, int timeout, RcimNativeStringCallback callback) {
    RcClientJNI.engineConnect(enginePtr, token, timeout, RcimNativeStringCallback.getCPtr(callback), callback);
  }

  public static void engineSetConnectionStatusListener(long enginePtr, RcimNativeIntListener listener) {
    RcClientJNI.engineSetConnectionStatusListener(enginePtr, RcimNativeIntListener.getCPtr(listener), listener);
  }

  public static void engineSendMessage(long enginePtr, RcimMessageBox msgBox, RcimNativeSendMessageCallback sendMsgCallback) {
    RcClientJNI.engineSendMessage(enginePtr, RcimMessageBox.getCPtr(msgBox), msgBox, RcimNativeSendMessageCallback.getCPtr(sendMsgCallback), sendMsgCallback);
  }

}
