/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.internal.swig;

public class RcimAndroidConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimAndroidConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimAndroidConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimAndroidConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RcClientJNI.delete_RcimAndroidConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimAndroidConfig fromPointer(long cPtr) {
    return new RcimAndroidConfig(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setNotification_id(String value) {
    RcClientJNI.RcimAndroidConfig_notification_id_set(swigCPtr, this, value);
  }

  public String getNotification_id() {
    return RcClientJNI.RcimAndroidConfig_notification_id_get(swigCPtr, this);
  }

  public void setMi_channel_id(String value) {
    RcClientJNI.RcimAndroidConfig_mi_channel_id_set(swigCPtr, this, value);
  }

  public String getMi_channel_id() {
    return RcClientJNI.RcimAndroidConfig_mi_channel_id_get(swigCPtr, this);
  }

  public void setHw_channel_id(String value) {
    RcClientJNI.RcimAndroidConfig_hw_channel_id_set(swigCPtr, this, value);
  }

  public String getHw_channel_id() {
    return RcClientJNI.RcimAndroidConfig_hw_channel_id_get(swigCPtr, this);
  }

  public void setHw_importance(String value) {
    RcClientJNI.RcimAndroidConfig_hw_importance_set(swigCPtr, this, value);
  }

  public String getHw_importance() {
    return RcClientJNI.RcimAndroidConfig_hw_importance_get(swigCPtr, this);
  }

  public void setHw_image_url(String value) {
    RcClientJNI.RcimAndroidConfig_hw_image_url_set(swigCPtr, this, value);
  }

  public String getHw_image_url() {
    return RcClientJNI.RcimAndroidConfig_hw_image_url_get(swigCPtr, this);
  }

  public void setHw_category(String value) {
    RcClientJNI.RcimAndroidConfig_hw_category_set(swigCPtr, this, value);
  }

  public String getHw_category() {
    return RcClientJNI.RcimAndroidConfig_hw_category_get(swigCPtr, this);
  }

  public void setHonor_importance(String value) {
    RcClientJNI.RcimAndroidConfig_honor_importance_set(swigCPtr, this, value);
  }

  public String getHonor_importance() {
    return RcClientJNI.RcimAndroidConfig_honor_importance_get(swigCPtr, this);
  }

  public void setHonor_image_url(String value) {
    RcClientJNI.RcimAndroidConfig_honor_image_url_set(swigCPtr, this, value);
  }

  public String getHonor_image_url() {
    return RcClientJNI.RcimAndroidConfig_honor_image_url_get(swigCPtr, this);
  }

  public void setOppo_channel_id(String value) {
    RcClientJNI.RcimAndroidConfig_oppo_channel_id_set(swigCPtr, this, value);
  }

  public String getOppo_channel_id() {
    return RcClientJNI.RcimAndroidConfig_oppo_channel_id_get(swigCPtr, this);
  }

  public void setVivo_category(String value) {
    RcClientJNI.RcimAndroidConfig_vivo_category_set(swigCPtr, this, value);
  }

  public String getVivo_category() {
    return RcClientJNI.RcimAndroidConfig_vivo_category_get(swigCPtr, this);
  }

  public void setVivo_type(String value) {
    RcClientJNI.RcimAndroidConfig_vivo_type_set(swigCPtr, this, value);
  }

  public String getVivo_type() {
    return RcClientJNI.RcimAndroidConfig_vivo_type_get(swigCPtr, this);
  }

  public void setFcm_channel_id(String value) {
    RcClientJNI.RcimAndroidConfig_fcm_channel_id_set(swigCPtr, this, value);
  }

  public String getFcm_channel_id() {
    return RcClientJNI.RcimAndroidConfig_fcm_channel_id_get(swigCPtr, this);
  }

  public void setFcm_collapse_key(String value) {
    RcClientJNI.RcimAndroidConfig_fcm_collapse_key_set(swigCPtr, this, value);
  }

  public String getFcm_collapse_key() {
    return RcClientJNI.RcimAndroidConfig_fcm_collapse_key_get(swigCPtr, this);
  }

  public void setFcm_image_url(String value) {
    RcClientJNI.RcimAndroidConfig_fcm_image_url_set(swigCPtr, this, value);
  }

  public String getFcm_image_url() {
    return RcClientJNI.RcimAndroidConfig_fcm_image_url_get(swigCPtr, this);
  }

  public RcimAndroidConfig() {
    this(RcClientJNI.new_RcimAndroidConfig(), true);
  }

}
