/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.internal.swig;

public class RcimReceivedStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimReceivedStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimReceivedStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimReceivedStatus obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RcClientJNI.delete_RcimReceivedStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimReceivedStatus fromPointer(long cPtr) {
    return new RcimReceivedStatus(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setIs_read(boolean value) {
    RcClientJNI.RcimReceivedStatus_is_read_set(swigCPtr, this, value);
  }

  public boolean getIs_read() {
    return RcClientJNI.RcimReceivedStatus_is_read_get(swigCPtr, this);
  }

  public void setIs_listened(boolean value) {
    RcClientJNI.RcimReceivedStatus_is_listened_set(swigCPtr, this, value);
  }

  public boolean getIs_listened() {
    return RcClientJNI.RcimReceivedStatus_is_listened_get(swigCPtr, this);
  }

  public void setIs_download(boolean value) {
    RcClientJNI.RcimReceivedStatus_is_download_set(swigCPtr, this, value);
  }

  public boolean getIs_download() {
    return RcClientJNI.RcimReceivedStatus_is_download_get(swigCPtr, this);
  }

  public void setIs_retrieved(boolean value) {
    RcClientJNI.RcimReceivedStatus_is_retrieved_set(swigCPtr, this, value);
  }

  public boolean getIs_retrieved() {
    return RcClientJNI.RcimReceivedStatus_is_retrieved_get(swigCPtr, this);
  }

  public void setIs_multiple_received(boolean value) {
    RcClientJNI.RcimReceivedStatus_is_multiple_received_set(swigCPtr, this, value);
  }

  public boolean getIs_multiple_received() {
    return RcClientJNI.RcimReceivedStatus_is_multiple_received_get(swigCPtr, this);
  }

  public RcimReceivedStatus() {
    this(RcClientJNI.new_RcimReceivedStatus(), true);
  }

}
