//
// Created by Qi on 2025/8/6.
//

#ifndef MYSWIGDEMO_NATIVESENDMESSAGECALLBACK_JNI_H
#define MYSWIGDEMO_NATIVESENDMESSAGECALLBACK_JNI_H
namespace rcim {

} // namespace rcim
#endif //MYSWIGDEMO_NATIVESENDMESSAGECALLBACK_JNI_H
