/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class MapString extends java.util.AbstractMap<String, String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MapString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MapString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MapString obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_MapString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public String get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public String put(String key, String value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public String remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      String oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, String>> entrySet() {
    java.util.Set<Entry<String, String>> setToReturn =
        new java.util.HashSet<Entry<String, String>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, String>() {
        private Iterator iterator;

        private Entry<String, String> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public String getValue() {
          return iterator.getValue();
        }

        public String setValue(String newValue) {
          String oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public MapString() {
    this(rc_adapterJNI.new_MapString__SWIG_0(), true);
  }

  public MapString(MapString other) {
    this(rc_adapterJNI.new_MapString__SWIG_1(MapString.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rc_adapterJNI.delete_MapString_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private MapString.Iterator getNextUnchecked() {
      return new MapString.Iterator(rc_adapterJNI.MapString_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(MapString.Iterator other) {
      return rc_adapterJNI.MapString_Iterator_isNot(swigCPtr, this, MapString.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return rc_adapterJNI.MapString_Iterator_getKey(swigCPtr, this);
    }
  
    private String getValue() {
      return rc_adapterJNI.MapString_Iterator_getValue(swigCPtr, this);
    }
  
    private void setValue(String newValue) {
      rc_adapterJNI.MapString_Iterator_setValue(swigCPtr, this, newValue);
    }
  
  }

  public boolean isEmpty() {
    return rc_adapterJNI.MapString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    rc_adapterJNI.MapString_clear(swigCPtr, this);
  }

  private MapString.Iterator find(String key) {
    return new MapString.Iterator(rc_adapterJNI.MapString_find(swigCPtr, this, key), true);
  }

  private MapString.Iterator begin() {
    return new MapString.Iterator(rc_adapterJNI.MapString_begin(swigCPtr, this), true);
  }

  private MapString.Iterator end() {
    return new MapString.Iterator(rc_adapterJNI.MapString_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return rc_adapterJNI.MapString_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return rc_adapterJNI.MapString_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, String value) {
    rc_adapterJNI.MapString_putUnchecked(swigCPtr, this, key, value);
  }

  private void removeUnchecked(MapString.Iterator itr) {
    rc_adapterJNI.MapString_removeUnchecked(swigCPtr, this, MapString.Iterator.getCPtr(itr), itr);
  }

}
