/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class rc_adapter {
  public static int createEngineBuilder(RcimEngineBuilderParam param, long[] OUTPUT) {
    return rc_adapterJNI.createEngineBuilder(RcimEngineBuilderParam.getCPtr(param), param, OUTPUT);
  }

  public static int engineBuilderBuild(long builderPtr, long[] OUTPUT) {
    return rc_adapterJNI.engineBuilderBuild(builderPtr, OUTPUT);
  }

  public static long newSdkVersionArray(int size) {
    return rc_adapterJNI.newSdkVersionArray(size);
  }

  public static void insertSdkVersionArray(long ptr, long[] ptrArr, int size) {
    rc_adapterJNI.insertSdkVersionArray(ptr, ptrArr, size);
  }

  public static void freeSdkVersionArray(long ptr) {
    rc_adapterJNI.freeSdkVersionArray(ptr);
  }

  public static int engineBuilderSetStorePath(long builderPtr, String storePath) {
    return rc_adapterJNI.engineBuilderSetStorePath(builderPtr, storePath);
  }

  public static void engineConnect(long enginePtr, String token, int timeout, RcimNativeStringCallback callback) {
    rc_adapterJNI.engineConnect(enginePtr, token, timeout, RcimNativeStringCallback.getCPtr(callback), callback);
  }

  public static void engineSetConnectionStatusListener(long enginePtr, RcimNativeIntListener listener) {
    rc_adapterJNI.engineSetConnectionStatusListener(enginePtr, RcimNativeIntListener.getCPtr(listener), listener);
  }

  public static void engineSendMessage(long enginePtr, RcimMessageBox msgBox, RcimNativeSendMessageCallback sendMsgCallback) {
    rc_adapterJNI.engineSendMessage(enginePtr, RcimMessageBox.getCPtr(msgBox), msgBox, RcimNativeSendMessageCallback.getCPtr(sendMsgCallback), sendMsgCallback);
  }

}
