/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class rc_adapterJNI {
  public final static native long new_MapString__SWIG_0();
  public final static native long new_MapString__SWIG_1(long jarg1, MapString jarg1_);
  public final static native long MapString_Iterator_getNextUnchecked(long jarg1, MapString.Iterator jarg1_);
  public final static native boolean MapString_Iterator_isNot(long jarg1, MapString.Iterator jarg1_, long jarg2, MapString.Iterator jarg2_);
  public final static native String MapString_Iterator_getKey(long jarg1, MapString.Iterator jarg1_);
  public final static native String MapString_Iterator_getValue(long jarg1, MapString.Iterator jarg1_);
  public final static native void MapString_Iterator_setValue(long jarg1, MapString.Iterator jarg1_, String jarg2);
  public final static native void delete_MapString_Iterator(long jarg1);
  public final static native boolean MapString_isEmpty(long jarg1, MapString jarg1_);
  public final static native void MapString_clear(long jarg1, MapString jarg1_);
  public final static native long MapString_find(long jarg1, MapString jarg1_, String jarg2);
  public final static native long MapString_begin(long jarg1, MapString jarg1_);
  public final static native long MapString_end(long jarg1, MapString jarg1_);
  public final static native int MapString_sizeImpl(long jarg1, MapString jarg1_);
  public final static native boolean MapString_containsImpl(long jarg1, MapString jarg1_, String jarg2);
  public final static native void MapString_putUnchecked(long jarg1, MapString jarg1_, String jarg2, String jarg3);
  public final static native void MapString_removeUnchecked(long jarg1, MapString jarg1_, long jarg2, MapString.Iterator jarg2_);
  public final static native void delete_MapString(long jarg1);
  public final static native long new_VectorInt__SWIG_0();
  public final static native long new_VectorInt__SWIG_1(long jarg1, VectorInt jarg1_);
  public final static native long VectorInt_capacity(long jarg1, VectorInt jarg1_);
  public final static native void VectorInt_reserve(long jarg1, VectorInt jarg1_, long jarg2);
  public final static native boolean VectorInt_isEmpty(long jarg1, VectorInt jarg1_);
  public final static native void VectorInt_clear(long jarg1, VectorInt jarg1_);
  public final static native long new_VectorInt__SWIG_2(int jarg1, int jarg2);
  public final static native int VectorInt_doSize(long jarg1, VectorInt jarg1_);
  public final static native void VectorInt_doAdd__SWIG_0(long jarg1, VectorInt jarg1_, int jarg2);
  public final static native void VectorInt_doAdd__SWIG_1(long jarg1, VectorInt jarg1_, int jarg2, int jarg3);
  public final static native int VectorInt_doRemove(long jarg1, VectorInt jarg1_, int jarg2);
  public final static native int VectorInt_doGet(long jarg1, VectorInt jarg1_, int jarg2);
  public final static native int VectorInt_doSet(long jarg1, VectorInt jarg1_, int jarg2, int jarg3);
  public final static native void VectorInt_doRemoveRange(long jarg1, VectorInt jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorInt(long jarg1);
  public final static native long new_VectorLong__SWIG_0();
  public final static native long new_VectorLong__SWIG_1(long jarg1, VectorLong jarg1_);
  public final static native long VectorLong_capacity(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_reserve(long jarg1, VectorLong jarg1_, long jarg2);
  public final static native boolean VectorLong_isEmpty(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_clear(long jarg1, VectorLong jarg1_);
  public final static native long new_VectorLong__SWIG_2(int jarg1, long jarg2);
  public final static native int VectorLong_doSize(long jarg1, VectorLong jarg1_);
  public final static native void VectorLong_doAdd__SWIG_0(long jarg1, VectorLong jarg1_, long jarg2);
  public final static native void VectorLong_doAdd__SWIG_1(long jarg1, VectorLong jarg1_, int jarg2, long jarg3);
  public final static native long VectorLong_doRemove(long jarg1, VectorLong jarg1_, int jarg2);
  public final static native long VectorLong_doGet(long jarg1, VectorLong jarg1_, int jarg2);
  public final static native long VectorLong_doSet(long jarg1, VectorLong jarg1_, int jarg2, long jarg3);
  public final static native void VectorLong_doRemoveRange(long jarg1, VectorLong jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorLong(long jarg1);
  public final static native int create_engine_builder(java.lang.Object jarg1, long jarg2, VectorLong jarg2_);
  public final static native int engine_builder_set_store_path(long jarg1, String jarg2);
  public final static native int engine_builder_build(long jarg1, long jarg2, VectorLong jarg2_);
  public final static native void engine_connect(long jarg1, String jarg2, int jarg3, java.lang.Object jarg4);
  public final static native void engine_set_connection_status_listener(long jarg1, java.lang.Object jarg2);
}
