/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class rc_adapter {
  public static int create_engine_builder(java.lang.Object javaParam, VectorLong outBuilderPtrArray) {
    return rc_adapterJNI.create_engine_builder(javaParam, VectorLong.getCPtr(outBuilderPtrArray), outBuilderPtrArray);
  }

  public static int engine_builder_set_store_path(long builderPtr, String storePath) {
    return rc_adapterJNI.engine_builder_set_store_path(builderPtr, storePath);
  }

  public static int engine_builder_build(long builderPtr, VectorLong outEngineArray) {
    return rc_adapterJNI.engine_builder_build(builderPtr, VectorLong.getCPtr(outEngineArray), outEngineArray);
  }

  public static void engine_connect(long enginePtr, String token, int timeout, java.lang.Object callback) {
    rc_adapterJNI.engine_connect(enginePtr, token, timeout, callback);
  }

  public static void engine_set_connection_status_listener(long enginePtr, java.lang.Object listener) {
    rc_adapterJNI.engine_set_connection_status_listener(enginePtr, listener);
  }

}
