/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimReadReceiptUserInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimReadReceiptUserInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimReadReceiptUserInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimReadReceiptUserInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimReadReceiptUserInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * delete() 方法名太过于普通，所以新增 swigDelete()
 * 使用该方法进行释放，不要使用 delete()
 * 方便进行代码释放的检查
 * */
public synchronized void swigDelete() {
    delete();
}

  public void setSender_id(String value) {
    rc_adapterJNI.RcimReadReceiptUserInfo_sender_id_set(swigCPtr, this, value);
  }

  public String getSender_id() {
    return rc_adapterJNI.RcimReadReceiptUserInfo_sender_id_get(swigCPtr, this);
  }

  public void setTimestamp(java.math.BigInteger value) {
    rc_adapterJNI.RcimReadReceiptUserInfo_timestamp_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTimestamp() {
    return rc_adapterJNI.RcimReadReceiptUserInfo_timestamp_get(swigCPtr, this);
  }

  public void setMentioned(boolean value) {
    rc_adapterJNI.RcimReadReceiptUserInfo_mentioned_set(swigCPtr, this, value);
  }

  public boolean getMentioned() {
    return rc_adapterJNI.RcimReadReceiptUserInfo_mentioned_get(swigCPtr, this);
  }

  public RcimReadReceiptUserInfo() {
    this(rc_adapterJNI.new_RcimReadReceiptUserInfo(), true);
  }

}
