/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimEngineBuilderParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimEngineBuilderParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimEngineBuilderParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimEngineBuilderParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimEngineBuilderParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApp_key(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_app_key_set(swigCPtr, this, value);
  }

  public String getApp_key() {
    return rc_adapterJNI.RcimEngineBuilderParam_app_key_get(swigCPtr, this);
  }

  public void setPlatform(int value) {
    rc_adapterJNI.RcimEngineBuilderParam_platform_set(swigCPtr, this, value);
  }

  public int getPlatform() {
    return rc_adapterJNI.RcimEngineBuilderParam_platform_get(swigCPtr, this);
  }

  public void setDevice_id(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_device_id_set(swigCPtr, this, value);
  }

  public String getDevice_id() {
    return rc_adapterJNI.RcimEngineBuilderParam_device_id_get(swigCPtr, this);
  }

  public void setPackage_name(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_package_name_set(swigCPtr, this, value);
  }

  public String getPackage_name() {
    return rc_adapterJNI.RcimEngineBuilderParam_package_name_get(swigCPtr, this);
  }

  public void setImlib_version(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_imlib_version_set(swigCPtr, this, value);
  }

  public String getImlib_version() {
    return rc_adapterJNI.RcimEngineBuilderParam_imlib_version_get(swigCPtr, this);
  }

  public void setDevice_model(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_device_model_set(swigCPtr, this, value);
  }

  public String getDevice_model() {
    return rc_adapterJNI.RcimEngineBuilderParam_device_model_get(swigCPtr, this);
  }

  public void setDevice_manufacturer(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_device_manufacturer_set(swigCPtr, this, value);
  }

  public String getDevice_manufacturer() {
    return rc_adapterJNI.RcimEngineBuilderParam_device_manufacturer_get(swigCPtr, this);
  }

  public void setOs_version(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_os_version_set(swigCPtr, this, value);
  }

  public String getOs_version() {
    return rc_adapterJNI.RcimEngineBuilderParam_os_version_get(swigCPtr, this);
  }

  public void setSdk_version_vec(RcimSDKVersion value) {
    rc_adapterJNI.RcimEngineBuilderParam_sdk_version_vec_set(swigCPtr, this, RcimSDKVersion.getCPtr(value), value);
  }

  public RcimSDKVersion getSdk_version_vec() {
    long cPtr = rc_adapterJNI.RcimEngineBuilderParam_sdk_version_vec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimSDKVersion(cPtr, false);
  }

  public void setSdk_version_vec_len(int value) {
    rc_adapterJNI.RcimEngineBuilderParam_sdk_version_vec_len_set(swigCPtr, this, value);
  }

  public int getSdk_version_vec_len() {
    return rc_adapterJNI.RcimEngineBuilderParam_sdk_version_vec_len_get(swigCPtr, this);
  }

  public void setApp_version(String value) {
    rc_adapterJNI.RcimEngineBuilderParam_app_version_set(swigCPtr, this, value);
  }

  public String getApp_version() {
    return rc_adapterJNI.RcimEngineBuilderParam_app_version_get(swigCPtr, this);
  }

  public RcimEngineBuilderParam() {
    this(rc_adapterJNI.new_RcimEngineBuilderParam(), true);
  }

}
