/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimSDKVersion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimSDKVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimSDKVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimSDKVersion obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimSDKVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/** 静态工厂方法：从 C 指针构建 RcimMessageBox 对象 */
public static RcimSDKVersion fromPointer(long cPtr) {
    return new RcimSDKVersion(cPtr, false);
}

/** 获取原始指针 */
public long getCPtr() {
    return swigCPtr;
}

  public void setName(String value) {
    rc_adapterJNI.RcimSDKVersion_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return rc_adapterJNI.RcimSDKVersion_name_get(swigCPtr, this);
  }

  public void setVersion(String value) {
    rc_adapterJNI.RcimSDKVersion_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return rc_adapterJNI.RcimSDKVersion_version_get(swigCPtr, this);
  }

  public RcimSDKVersion() {
    this(rc_adapterJNI.new_RcimSDKVersion(), true);
  }

}
