/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimIosConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimIosConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimIosConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimIosConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimIosConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimIosConfig fromPointer(long cPtr) {
    return new RcimIosConfig(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setThread_id(String value) {
    rc_adapterJNI.RcimIosConfig_thread_id_set(swigCPtr, this, value);
  }

  public String getThread_id() {
    return rc_adapterJNI.RcimIosConfig_thread_id_get(swigCPtr, this);
  }

  public void setCategory(String value) {
    rc_adapterJNI.RcimIosConfig_category_set(swigCPtr, this, value);
  }

  public String getCategory() {
    return rc_adapterJNI.RcimIosConfig_category_get(swigCPtr, this);
  }

  public void setApns_collapse_id(String value) {
    rc_adapterJNI.RcimIosConfig_apns_collapse_id_set(swigCPtr, this, value);
  }

  public String getApns_collapse_id() {
    return rc_adapterJNI.RcimIosConfig_apns_collapse_id_get(swigCPtr, this);
  }

  public void setRich_media_uri(String value) {
    rc_adapterJNI.RcimIosConfig_rich_media_uri_set(swigCPtr, this, value);
  }

  public String getRich_media_uri() {
    return rc_adapterJNI.RcimIosConfig_rich_media_uri_get(swigCPtr, this);
  }

  public void setInterruption_level(String value) {
    rc_adapterJNI.RcimIosConfig_interruption_level_set(swigCPtr, this, value);
  }

  public String getInterruption_level() {
    return rc_adapterJNI.RcimIosConfig_interruption_level_get(swigCPtr, this);
  }

  public RcimIosConfig() {
    this(rc_adapterJNI.new_RcimIosConfig(), true);
  }

}
