/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimPushConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimPushConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimPushConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimPushConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimPushConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimPushConfig fromPointer(long cPtr) {
    return new RcimPushConfig(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setDisable_push_title(boolean value) {
    rc_adapterJNI.RcimPushConfig_disable_push_title_set(swigCPtr, this, value);
  }

  public boolean getDisable_push_title() {
    return rc_adapterJNI.RcimPushConfig_disable_push_title_get(swigCPtr, this);
  }

  public void setPush_title(String value) {
    rc_adapterJNI.RcimPushConfig_push_title_set(swigCPtr, this, value);
  }

  public String getPush_title() {
    return rc_adapterJNI.RcimPushConfig_push_title_get(swigCPtr, this);
  }

  public void setPush_content(String value) {
    rc_adapterJNI.RcimPushConfig_push_content_set(swigCPtr, this, value);
  }

  public String getPush_content() {
    return rc_adapterJNI.RcimPushConfig_push_content_get(swigCPtr, this);
  }

  public void setPush_data(String value) {
    rc_adapterJNI.RcimPushConfig_push_data_set(swigCPtr, this, value);
  }

  public String getPush_data() {
    return rc_adapterJNI.RcimPushConfig_push_data_get(swigCPtr, this);
  }

  public void setForce_show_detail_content(boolean value) {
    rc_adapterJNI.RcimPushConfig_force_show_detail_content_set(swigCPtr, this, value);
  }

  public boolean getForce_show_detail_content() {
    return rc_adapterJNI.RcimPushConfig_force_show_detail_content_get(swigCPtr, this);
  }

  public void setIos_config(RcimIosConfig value) {
    rc_adapterJNI.RcimPushConfig_ios_config_set(swigCPtr, this, RcimIosConfig.getCPtr(value), value);
  }

  public RcimIosConfig getIos_config() {
    long cPtr = rc_adapterJNI.RcimPushConfig_ios_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimIosConfig(cPtr, false);
  }

  public void setAndroid_config(RcimAndroidConfig value) {
    rc_adapterJNI.RcimPushConfig_android_config_set(swigCPtr, this, RcimAndroidConfig.getCPtr(value), value);
  }

  public RcimAndroidConfig getAndroid_config() {
    long cPtr = rc_adapterJNI.RcimPushConfig_android_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimAndroidConfig(cPtr, false);
  }

  public void setHarmony_config(RcimHarmonyConfig value) {
    rc_adapterJNI.RcimPushConfig_harmony_config_set(swigCPtr, this, RcimHarmonyConfig.getCPtr(value), value);
  }

  public RcimHarmonyConfig getHarmony_config() {
    long cPtr = rc_adapterJNI.RcimPushConfig_harmony_config_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimHarmonyConfig(cPtr, false);
  }

  public RcimPushConfig() {
    this(rc_adapterJNI.new_RcimPushConfig(), true);
  }

}
