/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimHarmonyConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimHarmonyConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimHarmonyConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimHarmonyConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimHarmonyConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setImage_url(String value) {
    rc_adapterJNI.RcimHarmonyConfig_image_url_set(swigCPtr, this, value);
  }

  public String getImage_url() {
    return rc_adapterJNI.RcimHarmonyConfig_image_url_get(swigCPtr, this);
  }

  public void setCategory(String value) {
    rc_adapterJNI.RcimHarmonyConfig_category_set(swigCPtr, this, value);
  }

  public String getCategory() {
    return rc_adapterJNI.RcimHarmonyConfig_category_get(swigCPtr, this);
  }

  public RcimHarmonyConfig() {
    this(rc_adapterJNI.new_RcimHarmonyConfig(), true);
  }

}
