/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimReadReceiptInfoV2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimReadReceiptInfoV2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimReadReceiptInfoV2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimReadReceiptInfoV2 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        rc_adapterJNI.delete_RcimReadReceiptInfoV2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimReadReceiptInfoV2 fromPointer(long cPtr) {
    return new RcimReadReceiptInfoV2(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setHas_respond(boolean value) {
    rc_adapterJNI.RcimReadReceiptInfoV2_has_respond_set(swigCPtr, this, value);
  }

  public boolean getHas_respond() {
    return rc_adapterJNI.RcimReadReceiptInfoV2_has_respond_get(swigCPtr, this);
  }

  public void setRespond_user_vec(RcimReadReceiptUserInfo value) {
    rc_adapterJNI.RcimReadReceiptInfoV2_respond_user_vec_set(swigCPtr, this, RcimReadReceiptUserInfo.getCPtr(value), value);
  }

  public RcimReadReceiptUserInfo getRespond_user_vec() {
    long cPtr = rc_adapterJNI.RcimReadReceiptInfoV2_respond_user_vec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimReadReceiptUserInfo(cPtr, false);
  }

  public void setRespond_user_vec_len(int value) {
    rc_adapterJNI.RcimReadReceiptInfoV2_respond_user_vec_len_set(swigCPtr, this, value);
  }

  public int getRespond_user_vec_len() {
    return rc_adapterJNI.RcimReadReceiptInfoV2_respond_user_vec_len_get(swigCPtr, this);
  }

  public void setRead_count(long value) {
    rc_adapterJNI.RcimReadReceiptInfoV2_read_count_set(swigCPtr, this, value);
  }

  public long getRead_count() {
    return rc_adapterJNI.RcimReadReceiptInfoV2_read_count_get(swigCPtr, this);
  }

  public void setTotal_count(long value) {
    rc_adapterJNI.RcimReadReceiptInfoV2_total_count_set(swigCPtr, this, value);
  }

  public long getTotal_count() {
    return rc_adapterJNI.RcimReadReceiptInfoV2_total_count_get(swigCPtr, this);
  }

  public RcimReadReceiptInfoV2() {
    this(rc_adapterJNI.new_RcimReadReceiptInfoV2(), true);
  }

}
