/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.imlib.swig;

public class RcimEngineBuilderParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcimEngineBuilderParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcimEngineBuilderParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RcimEngineBuilderParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RcClientJNI.delete_RcimEngineBuilderParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

/**
 * 该方法由配置生成<p>
 * delete() 方法名太过于普通，所以新增 swigDelete()<p>
 * 使用该方法进行释放，不要使用 delete()<p>
 * 方便进行代码创建、释放的检查
 */
public synchronized void swigDelete() {
    delete();
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 静态工厂方法：从 C 指针构建该对象
 */
public static RcimEngineBuilderParam fromPointer(long cPtr) {
    return new RcimEngineBuilderParam(cPtr, false);
}

/**
 * 该方法由配置生成<p>
 * WARNING： 原则上不能调用该方法，除非你明确知道你需要这个方法<p>
 * 获取原始指针
 */
public long getCPtr() {
    return swigCPtr;
}

  public void setApp_key(String value) {
    RcClientJNI.RcimEngineBuilderParam_app_key_set(swigCPtr, this, value);
  }

  public String getApp_key() {
    return RcClientJNI.RcimEngineBuilderParam_app_key_get(swigCPtr, this);
  }

  public void setPlatform(int value) {
    RcClientJNI.RcimEngineBuilderParam_platform_set(swigCPtr, this, value);
  }

  public int getPlatform() {
    return RcClientJNI.RcimEngineBuilderParam_platform_get(swigCPtr, this);
  }

  public void setDevice_id(String value) {
    RcClientJNI.RcimEngineBuilderParam_device_id_set(swigCPtr, this, value);
  }

  public String getDevice_id() {
    return RcClientJNI.RcimEngineBuilderParam_device_id_get(swigCPtr, this);
  }

  public void setPackage_name(String value) {
    RcClientJNI.RcimEngineBuilderParam_package_name_set(swigCPtr, this, value);
  }

  public String getPackage_name() {
    return RcClientJNI.RcimEngineBuilderParam_package_name_get(swigCPtr, this);
  }

  public void setImlib_version(String value) {
    RcClientJNI.RcimEngineBuilderParam_imlib_version_set(swigCPtr, this, value);
  }

  public String getImlib_version() {
    return RcClientJNI.RcimEngineBuilderParam_imlib_version_get(swigCPtr, this);
  }

  public void setDevice_model(String value) {
    RcClientJNI.RcimEngineBuilderParam_device_model_set(swigCPtr, this, value);
  }

  public String getDevice_model() {
    return RcClientJNI.RcimEngineBuilderParam_device_model_get(swigCPtr, this);
  }

  public void setDevice_manufacturer(String value) {
    RcClientJNI.RcimEngineBuilderParam_device_manufacturer_set(swigCPtr, this, value);
  }

  public String getDevice_manufacturer() {
    return RcClientJNI.RcimEngineBuilderParam_device_manufacturer_get(swigCPtr, this);
  }

  public void setOs_version(String value) {
    RcClientJNI.RcimEngineBuilderParam_os_version_set(swigCPtr, this, value);
  }

  public String getOs_version() {
    return RcClientJNI.RcimEngineBuilderParam_os_version_get(swigCPtr, this);
  }

  public void setSdk_version_vec(RcimSDKVersion value) {
    RcClientJNI.RcimEngineBuilderParam_sdk_version_vec_set(swigCPtr, this, RcimSDKVersion.getCPtr(value), value);
  }

  public RcimSDKVersion getSdk_version_vec() {
    long cPtr = RcClientJNI.RcimEngineBuilderParam_sdk_version_vec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RcimSDKVersion(cPtr, false);
  }

  public void setSdk_version_vec_len(int value) {
    RcClientJNI.RcimEngineBuilderParam_sdk_version_vec_len_set(swigCPtr, this, value);
  }

  public int getSdk_version_vec_len() {
    return RcClientJNI.RcimEngineBuilderParam_sdk_version_vec_len_get(swigCPtr, this);
  }

  public void setApp_version(String value) {
    RcClientJNI.RcimEngineBuilderParam_app_version_set(swigCPtr, this, value);
  }

  public String getApp_version() {
    return RcClientJNI.RcimEngineBuilderParam_app_version_get(swigCPtr, this);
  }

  public RcimEngineBuilderParam() {
    this(RcClientJNI.new_RcimEngineBuilderParam(), true);
  }

}
