/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.rong.rust.imlibv2.jni;

public class example {
  public static int add(int a, int b) {
    return exampleJNI.add(a, b);
  }

}
