/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_rc_adapter_WRAP_H_
#define SWIG_rc_adapter_WRAP_H_

class SwigDirector_ConnectCallback : public ConnectCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ConnectCallback(JNIEnv *jenv);
    virtual ~SwigDirector_ConnectCallback();
    virtual void onConnect(int code,char const *user_id);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_NativeSendMessageCallback : public NativeSendMessageCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_NativeSendMessageCallback(JNIEnv *jenv);
    virtual ~SwigDirector_NativeSendMessageCallback();
    virtual void onSave(RcimMessageBox const *msg);
    virtual void onResult(int code,RcimMessageBox const *msg);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_NativeIntListener : public NativeIntListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_NativeIntListener(JNIEnv *jenv);
    virtual ~SwigDirector_NativeIntListener();
    virtual void onChanged(int value);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
