/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_RcClient_WRAP_H_
#define SWIG_RcClient_WRAP_H_

class SwigDirector_RcimNativeStringCallback : public RcimNativeStringCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RcimNativeStringCallback(JNIEnv *jenv);
    virtual ~SwigDirector_RcimNativeStringCallback();
    virtual void onResult(RcimNativeStringCallback *deleteThis,int code,char const *value);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_RcimNativeSendMessageCallback : public RcimNativeSendMessageCallback, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RcimNativeSendMessageCallback(JNIEnv *jenv);
    virtual ~SwigDirector_RcimNativeSendMessageCallback();
    virtual void onSave(RcimMessageBox const *nativeMsg);
    virtual void onResult(RcimNativeSendMessageCallback *deleteThis,int code,RcimMessageBox const *nativeMsg);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_RcimNativeIntListener : public RcimNativeIntListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_RcimNativeIntListener(JNIEnv *jenv);
    virtual ~SwigDirector_RcimNativeIntListener();
    virtual void onChanged(int value);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
